routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::get('/post', 'AdminPostsControl@post')->name('post');

Route::group(['middleware' => 'auth'], function() {
    Route::resource('/admin/users', 'AdminUsersControl');

    Route::resource('/admin/posts', 'AdminPostsControl');

    Route::resource('/admin/comments', 'AdminCommentsControl');

    Route::resource('/admin/media', 'AdminMediasControl');
    Route::post('/admin/media/upload', 'AdminMediasControl@upload');
    Route::delete('/admin/media/check', 'AdminMediasControl@check')->name('media.check');
    Route::get('/media/display', 'AdminMediasControl@display')->name('media.display');
    Route::get('/media/fetch', 'AdminMediasControl@fetch')->name('media.fetch');

    Route::resource('/admin/comments', 'AdminCommentsControl');
    Route::post('/admin/comments/add/{post_id}', 'AdminCommentsControl@add');

    Route::resource('/admin/replies', 'AdminRepliesControl');
    Route::post('/admin/replies/add/{comment_id}', 'AdminRepliesControl@add');
});

Route::group(['middleware' => 'admin'], function() {
    Route::resource('/admin/categories', 'AdminCategoriesControl');
});

Route::get('/', function(){
    return view('admin.index');
});
Route::get('/admin', function(){
    return view('admin.index');
});

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    /**
     * The attributes that are mass assignable.
     * @var array
     */
    protected $fillable = [
        'body', 'post_id', 'user_id', 'is_active'
    ];

    /**
     * Defining BelongsTo Relationship.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }
    public function post()
    {
        return $this->belongsTo('App\Models\Post', 'post_id');
    }

    /**
     * Defining Has-Many Relationship.
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function hasReply()
    {
        return $this->hasMany('App\Models\Reply');
    }
}

resources/views/admin/comments/index.blade.php
@extends('layouts.admin')

@section('title', 'Comments')

@section('content')
    <h1 class="page-header">Comments
        @if(isset($post)) <small> / Title: {{$post->title}} - User: {{$post->user->name}}</small> @endif
    </h1>

    @if(sizeof($comments) > 0)
        <table class="table">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Author</th>
                    @unless(isset($post))
                        <th>Post</th>
                        <th>User</th>
                    @endunless
                    <th>Date</th>
                    <th>Comment</th>
                </tr>
            </thead>
            <tbody>
            @foreach($comments as $comment)
                <tr>
                    <td>{{$comment->id}}</td>
                    <td>{{$comment->user->name}}</td>
                    @unless(isset($post))
                        <td>{{$comment->post->title}}</td>
                        <td>{{$comment->post->user->name}}</td>
                    @endunless
                    <td>{{$comment->created_at->diffForHumans()}}</td>
                    <td>{{str_limit($comment->body,40)}}</td>
                    <td><a href="{{route('posts.show',$comment->post->id)}}">View Post</a></td>
                    @if(count($comment->hasReply) > 0)
                        <td><a href="{{route('replies.show',$comment->id)}}">View Replies</a></td>
                    @else
                        <td> - </td>
                    @endif
                    <td>
                        @if($comment->is_active == 1)
                        {!! Form::open(['method'=>'PATCH', 'action'=> ['AdminCommentsControl@update', $comment->id]]) !!}
                            <input type="hidden" name="is_active" value="0">
                            <div class="form-group">
                                {!! Form::submit('Un-approve', ['class'=>'btn btn-success']) !!}
                            </div>
                        {!! Form::close() !!}
                        @else
                        {!! Form::open(['method'=>'PATCH', 'action'=> ['AdminCommentsControl@update', $comment->id]]) !!}
                            <input type="hidden" name="is_active" value="1">
                            <div class="form-group">
                                {!! Form::submit('Approve', ['class'=>'btn btn-info']) !!}
                            </div>
                        {!! Form::close() !!}
                        @endif
                    </td>
                    <td>
                        {!! Form::open(['method'=>'DELETE', 'action'=> ['AdminCommentsControl@destroy', $comment->id]]) !!}
                        <div class="form-group">
                            {!! Form::submit('Delete', ['class'=>'btn btn-danger']) !!}
                        </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <h2>No Comment has been inserted</h2>
    @endif
@endsection