routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::get('/post', 'AdminPostsControl@post')->name('post');

Route::group(['middleware' => 'auth'], function() {
    Route::resource('/admin/users', 'AdminUsersControl');

    Route::resource('/admin/posts', 'AdminPostsControl');

    Route::resource('/admin/comments', 'AdminCommentsControl');

    Route::resource('/admin/media', 'AdminMediasControl');
    Route::post('/admin/media/upload', 'AdminMediasControl@upload');
    Route::delete('/admin/media/check', 'AdminMediasControl@check')->name('media.check');
    Route::get('/media/display', 'AdminMediasControl@display')->name('media.display');
    Route::get('/media/fetch', 'AdminMediasControl@fetch')->name('media.fetch');

    Route::resource('/admin/comments', 'AdminCommentsControl');
    Route::post('/admin/comments/add/{post_id}', 'AdminCommentsControl@add');

    Route::resource('/admin/replies', 'AdminRepliesControl');
    Route::post('/admin/replies/add/{comment_id}', 'AdminRepliesControl@add');
});

Route::group(['middleware' => 'admin'], function() {
    Route::resource('/admin/categories', 'AdminCategoriesControl');
});

Route::get('/', function(){
    return view('admin.index');
});
Route::get('/admin', function(){
    return view('admin.index');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Assets\Cryptography;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'photo_id', 'is_active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Defining Accessors and Mutators.
     */
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = Cryptography::encrypt3($password);
    }
    public function getPasswordAttribute($password)
    {
        return Cryptography::decrypt3($password);
    }

    /**
     * Defining belongsTo Relationships
     */
    public function role()
    {
        return $this->belongsTo('App\Models\Role');
    }

    public function photo()
    {
        return $this->belongsTo('App\Models\Photo');
    }

    /**
     * Defining hasMany Relationship.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function manyPost()
    {
        return $this->hasMany('App\Models\Post');
    }

    /**
     * Methods for Authorizing
     */
    public function isAdmin()
    {
        return ($this->role->name == 'admin' && $this->is_active == 1);
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('title', 'Create User')

@section('content')
    <h1 class="page-header">Create User</h1>

    {!! Form::open(['method'=>'POST', 'action'=> 'AdminUsersControl@store','files'=>true]) !!}
        <div class="row">
            <div class="form-group col-md-8">
                {!! Form::label('name', 'Name:') !!}
                {!! Form::text('name', null, ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('email', 'Email:') !!}
                {!! Form::email('email', null, ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('role_id', 'Role:') !!}
                {!! Form::select('role_id', [''=>'Choose Options'] + $roles, null, ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('is_active', 'Status:') !!}
                {!! Form::select('is_active', array(1 => 'Active', 0=> 'Not Active'), 0, ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('photo_id', 'Photo:') !!} <br>
                <div class="btn btn-info btn-file">
                    {!! Form::file('photo_id', null, ['class'=>'form-control'])!!}
                </div>
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('password', 'Password:') !!}
                {!! Form::password('password', ['class'=>'form-control'])!!}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="form-group col-md-4">
                {!! Form::submit('Create User', ['class'=>'btn btn-block btn-primary']) !!}
            </div>
        </div>
    {!! Form::close() !!}

    @include('includes.form_error')

@endsection


@section('footer')
    
@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit User')

@section('content')
    <h1 class="page-header">Edit User</h1>

    <div class="row">
        <div class="col-md-3">
            <img src="{{$user->photo ? $user->photo->getPath() : 'http://placehold.it/400x400'}}" alt="" class="img-responsive img-rounded">
        </div>

        <div class="col-md-9">
        {!! Form::model($user, ['method'=>'PATCH', 'action'=> ['AdminUsersControl@update', $user->id],'files'=>true]) !!}
            <div class="row">
                <div class="form-group col-md-8">
                    {!! Form::label('name', 'Name:') !!}
                    {!! Form::text('name', null, ['class'=>'form-control'])!!}
                </div>
                <div class="form-group col-md-8">
                    {!! Form::label('email', 'Email:') !!}
                    {!! Form::email('email', null, ['class'=>'form-control'])!!}
                </div>
                <div class="form-group col-md-8">
                    {!! Form::label('role_id', 'Role:') !!}
                    {!! Form::select('role_id', $roles, null, ['class'=>'form-control'])!!}
                </div>
                <div class="form-group col-md-8">
                    {!! Form::label('is_active', 'Status:') !!}
                    {!! Form::select('is_active', array(1 => 'Active', 0=> 'Not Active'), null, ['class'=>'form-control'])!!}
                </div>
                <div class="form-group col-md-8">
                    {!! Form::label('photo_id', 'Photo:') !!} <br>
                    <div class="btn btn-info btn-file">
                        {!! Form::file('photo_id', null, ['class'=>'form-control'])!!}
                    </div>
                </div>
                <div class="form-group col-md-8">
                    {!! Form::label('password', 'Password:') !!}
                    {!! Form::password('password', ['class'=>'form-control', 'placeholder'=>'No change'])!!}
                </div>
            </div>
            <br>
            <div class="row">
                <div class="form-group col-md-4">
                    {!! Form::submit('Update User', ['class'=>'btn btn-block btn-primary']) !!}
                </div>
            </div>
        {!! Form::close() !!}

        {!! Form::open(['method'=>'DELETE', 'action'=> ['AdminUsersControl@destroy', $user->id]]) !!}
            <div class="row">
                <div class="form-group col-md-4">
                    {!! Form::submit('Delete user', ['class'=>'btn btn-block btn-danger']) !!}
                </div>
            </div>
        {!! Form::close() !!}
        </div>
    </div>

    <div class="row">
        @include('includes.form_error')
    </div>
@endsection


@section('footer')
    
@stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('title', 'Users List')

@section('content')
    <h1 class="page-header">Users List</h1>

    @if(Session::has('user_deleted'))
        <br>
        <p class="bg-warning">{{session('user_deleted')}}</p>
    @endif

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Role</th>
            <th>Status</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
        </thead>
        <tbody>

        @if($users)
            @foreach($users as $user)
                <tr>
                    <td>{{$user->id}}</td>
                    <td> <img height="50" src="{{$user->photo ? $user->photo->getPath() : 'http://placehold.it/200x200'}}" alt="" ></td>
                    <td><a href="{{route('users.edit', $user->id)}}">{{$user->name}}</a></td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->password}}</td>
                    <td>{{$user->role ? $user->role->name : 'No role'}}</td>
                    <td>{{$user->is_active == 1 ? 'Active' : 'Not Active' }}</td>
                    <td>{{$user->created_at->diffForHumans()}}</td>
                    <td>{{$user->updated_at->diffForHumans()}}</td>
                </tr>
            @endforeach
        @endif
        </tbody>
    </table>
@endsection


@section('footer')
    
@stop