routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Route::get('/post', 'AdminPostsControl@post')->name('post');

Route::group(['middleware' => 'auth'], function() {
    Route::resource('/admin/users', 'AdminUsersControl');

    Route::resource('/admin/posts', 'AdminPostsControl');

    Route::resource('/admin/comments', 'AdminCommentsControl');

    Route::resource('/admin/media', 'AdminMediasControl');
    Route::post('/admin/media/upload', 'AdminMediasControl@upload');
    Route::delete('/admin/media/check', 'AdminMediasControl@check')->name('media.check');
    Route::get('/media/display', 'AdminMediasControl@display')->name('media.display');
    Route::get('/media/fetch', 'AdminMediasControl@fetch')->name('media.fetch');

    Route::resource('/admin/comments', 'AdminCommentsControl');
    Route::post('/admin/comments/add/{post_id}', 'AdminCommentsControl@add');

    Route::resource('/admin/replies', 'AdminRepliesControl');
    Route::post('/admin/replies/add/{comment_id}', 'AdminRepliesControl@add');
});

Route::group(['middleware' => 'admin'], function() {
    Route::resource('/admin/categories', 'AdminCategoriesControl');
});

Route::get('/', function(){
    return view('admin.index');
});
Route::get('/admin', function(){
    return view('admin.index');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     * @var array
     */
    protected $fillable = [
        'title', 'body', 'user_id', 'photo_id'
    ];

    /**
     * Assign the soft delete option.
     */
    use SoftDeletes;
    protected $dates = ['deleted_at'];

    use Sluggable;
    use SluggableScopeHelpers;
    /**
     * Return the sluggable configuration array for this model.
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    /**
     * Defining BelongsTo Relationship.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

    public function photo()
    {
        return $this->belongsTo('App\Models\Photo', 'photo_id');
    }

    /**
     * Defining Has-Many Relationship.
     * @return \Illuminate\Database\Eloquent\Relations\hasMany
     */
    public function hasComment()
    {
        return $this->hasMany('App\Models\Comment');
    }

    /**
     * Defining Many-to-Many Relationship.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function manyCateg()
    {
        return $this->belongsToMany('App\Models\Category', 'cat_posts', 'post_id', 'categ_id');
    }

    /**
     * Custom Methods of Post management.
     */
    public function getCateg()
    {
        $cat_list = [];
        foreach ($this->manyCateg()->get() as $categ) {
            $cat_list[] = $categ->name;
        }
        return implode(' / ', $cat_list);
    }
    public function listCateg()
    {
        $cat_list = [null,null,null];
        $ind = 0;
        foreach ($this->manyCateg()->get() as $categ) {
            $cat_list[$ind++] = $categ->id;
        }
        return $cat_list;
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')

@section('title', 'Create Post')

@section('content')
    <h1 class="page-header">Create Post</h1>

    {!! Form::open(['method'=>'POST', 'action'=> 'AdminPostsControl@store', 'files'=>true]) !!}
        <div class="row">
            <div class="form-group col-md-8">
                {!! Form::label('title', 'Title:') !!}
                {!! Form::text('title', null, ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('categ[0]', 'Category:') !!}
                {!! Form::select('categ[0]', [''=>'Choose Category'] + $category, null, ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('categ[1]', 'Category:') !!}
                {!! Form::select('categ[1]', [''=>'Add Category'] + $category, null, ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('categ[2]', 'Category:') !!}
                {!! Form::select('categ[2]', [''=>'Add Category'] + $category, null, ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('photo_id', 'Photo:') !!} <br>
                <div class="btn btn-info btn-file">
                    {!! Form::file('photo_id', null,['class'=>'form-control'])!!}
                </div>
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('body', 'Description:') !!}
                {!! Form::textarea('body', null, ['class'=>'form-control'])!!}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="form-group col-md-4">
                {!! Form::submit('Create Post', ['class'=>'btn btn-primary']) !!}
            </div>
        </div>
    {!! Form::close() !!}

    @include('includes.form_error')
@stop

@section('scripts')
    @include('includes.tinyeditor')
@endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Post')

@section('content')
    <h1 class="page-header">Edit Post</h1>
    
    <div class="row">
        <div class="col-sm-3">
            <img src="{{$post->photo ? $post->photo->getPath() : 'http://placehold.it/400x400'}}" alt="" class="img-responsive">
        </div>

    <div class="col-sm-9">
    {!! Form::model($post, ['method'=>'PATCH', 'action'=> ['AdminPostsControl@update', $post->id], 'files'=>true]) !!}
        <div class="row">
            <div class="form-group col-md-8">
                {!! Form::label('title', 'Title:') !!}
                {!! Form::text('title', null, ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('categ[0]', 'Category:') !!}
                {!! Form::select('categ[0]', [''=>'Choose Category'] + $category, $categ[0], ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('categ[1]', 'Category:') !!}
                {!! Form::select('categ[1]', [''=>'Add Category'] + $category, $categ[1], ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('categ[2]', 'Category:') !!}
                {!! Form::select('categ[2]', [''=>'Add Category'] + $category, $categ[2], ['class'=>'form-control'])!!}
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('photo_id', 'Photo:') !!} <br>
                <div class="btn btn-info btn-file">
                    {!! Form::file('photo_id', null,['class'=>'form-control'])!!}
                </div>
            </div>
            <div class="form-group col-md-8">
                {!! Form::label('body', 'Description:') !!}
                {!! Form::textarea('body', null, ['class'=>'form-control'])!!}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="form-group col-md-4">
                {!! Form::submit('Update Post', ['class'=>'btn btn-block btn-primary']) !!}
            </div>
        </div>
    {!! Form::close() !!}

    {!! Form::open(['method'=>'DELETE', 'action'=> ['AdminPostsControl@destroy', $post->id]]) !!}
        <div class="row">
             <div class="form-group col-md-4">
                 {!! Form::submit('Delete Post', ['class'=>'btn btn-block btn-danger']) !!}
             </div>
        </div>
    {!! Form::close() !!}
    </div>
    </div>

    @include('includes.form_error')
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')

@section('title', 'Post List')

@section('content')
    <h1 class="page-header">Post List</h1>

    @if(Session::has('user_deleted'))
        <br>
        <p class="bg-warning">{{session('post_deleted')}}</p>
    @endif

    @if(sizeof($posts) > 0)
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Photo</th>
                    <th>Owner</th>
                    <th>Category</th>
                    <th>Title</th>
                    <th>Body</th>
                    <th>Comments</th>
                    <th>Created at</th>
                    <th>Update</th>
                </tr>
            </thead>
            <tbody>

            @foreach($posts as $post)
                <tr>
                    <td>{{$post->id}}</td>
                    <td><img height="50" src="{{$post->photo ? $post->photo->getPath()
                    : 'http://placehold.it/400x400' }}" alt=""></td>
                    <td>{{$post->user->name}}</td>
                    <td>{{$post->getCateg()}}</td>
                    <td><a href="{{route('posts.show', $post->slug)}}">{{$post->title}}</a></td>
                    <td><a href="{{route('posts.show', $post->slug)}}">{{str_limit($post->body, 20)}}</a></td>
                    @if(count($post->hasComment) > 0)
                        <td><a href="{{route('comments.show', $post->id)}}">View Comments</a></td>
                    @else
                        <td> - </td>
                    @endif
                    <td>{{$post->created_at->diffForhumans()}}</td>
                    <td>{{$post->updated_at->diffForhumans()}}</td>
                    <td><a href="{{route('posts.edit', $post->id)}}">Edit Post</a></td>
               </tr>
            @endforeach
            </tbody>
        </table>

        <div class="row">
            <div class="col-sm-6 col-sm-offset-5">
                {!! $posts->render() !!}
            </div>
        </div>
    @else
        <h2>No Post has been inserted</h2>
    @endif
@endsection

resources/views/admin/posts/show.blade.php
@extends('layouts.admin')

@section('title', 'Show Post')
@section('styles')
    <link rel="stylesheet" href="{{ asset('css/blog-post.css') }}" />
@endsection

@section('content')
    <h1 class="page-header">{{$post->title}}</h1>

    <div class="row">
        <!-- Blog Post Content Column -->
        <div class="col-lg-8">
            <div class="row">
                <div class="col-md-6 lead">  <!-- Author -->
                    by <a href="#">{{$post->user->name}}</a>
                </div>
                <div class="col-md-6">  <!-- Date/Time -->
                    <span class="glyphicon glyphicon-time"></span> Posted on {{$post->created_at->diffForHumans()}}
                </div>
            </div>
            <hr>
            <!-- Preview Image -->
            @if($post->photo)
                <img height="200" src="{{$post->photo->getPath()}}" alt="">
                <hr>
            @endif
            <!-- Post Content -->
            <p class="lead">{!! $post->body !!}</p>
            <!-- Comments Form -->
            <div class="well">
                {!! Form::open(['method'=>'POST', 'action'=> ['AdminCommentsControl@add', $post->id]]) !!}
                    <div class="row">
                        <div class="form-group col-md-10">
                            {!! Form::label('body', 'Leave a Comment:') !!}
                            {!! Form::textarea('body', null, ['rows'=>3, 'class'=>'form-control'])!!}
                        </div>
                        <div class="form-group col-md-2">
                            <br><br>
                            {!! Form::submit('Submit', ['class'=>'btn btn-primary pull-right']) !!}
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
            <hr>
            <!-- Comment -->
            <div class="media">
            @foreach($comments as $comment)
              <a class="pull-left" href="#">
                <img width="80" src="{{$comment->user->photo ? $comment->user->photo->getPath()
                : 'http://placehold.it/80x80'}}" alt=""></a>
              <div class="media-body">
                <h4 class="media-heading">{{$comment->user->name}}
                   <small>{{$comment->created_at->diffForHumans()}}</small>
                </h4>
                {{$comment->body}}
                  <br>
                <button class="btn btn-success pull-right" data-toggle="collapse"
                        data-target="#reply{{$comment->id}}"> Reply
                </button>
                <div class="media">
                    <br>
                  <div class="media-body">
                    <div class="well collapse" id="reply{{$comment->id}}">
                        {!! Form::open(['method'=>'POST', 'action'=> ['AdminRepliesControl@add', $comment->id]]) !!}
                        <div class="row">
                            <div class="form-group col-md-10">
                                {!! Form::label('body', 'Leave a Replay:') !!}
                                {!! Form::textarea('body', null, ['rows'=>2, 'class'=>'form-control'])!!}
                            </div>
                            <div class="form-group col-md-2">
                                <br><br>
                                {!! Form::submit('Submit', ['class'=>'btn btn-primary pull-right']) !!}
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                    @foreach($comment->hasReply()->whereIsActive(1)->get() as $reply)
                        <a class="pull-left" href="#">
                            <img width="64" src="{{$reply->user->photo ? $reply->user->photo->getPath()
                            : 'http://placehold.it/64x64'}}" alt=""></a>
                        <div class="media-body">
                            <h4 class="media-heading">{{$reply->user->name}}
                                <small>{{$reply->created_at->diffForHumans()}}</small>
                            </h4>
                            {{$reply->body}}
                        </div>
                        <br>
                    @endforeach
                  </div>
                </div>
              </div>
              <br>
            @endforeach
            </div>
        </div>

        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">
            <!-- Blog Search Well -->
            <div class="well">
                <h4>Blog Search</h4>
                <div class="input-group">
                    <input type="text" class="form-control">
                    <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                </div>
                <!-- /.input-group -->
            </div>
            <!-- Blog Categories Well -->
            <div class="well">
                <h4>Blog Categories</h4>
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            @foreach($post->manyCateg()->get() as $category)
                                <li><a href="{{route('categories.edit', $category->id)}}">{{$category->name}}</a></li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                <!-- /.row -->
            </div>

            <!-- Side Widget Well -->
            <div class="well">
                <h4>Side Widget Well</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
            </div>
        </div>
    </div>
    <!-- /.row -->
@endsection